[phases.setup]
nixPkgs = ["bun", "nodejs"]

[phases.install]
cmds = ["bun install", "bun add -D lightningcss-linux-x64-gnu"]

[phases.build]
cmds = ["bun run prisma generate", "bun run migrate deploy", "bun run build"]

[start]
cmd = "bun run preview"